# Generated by Django 5.2.12 on 2026-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(help_text="Video title", max_length=255)),
                ("description", models.TextField(help_text="Video description")),
                (
                    "thumbnail",
                    models.URLField(
                        blank=True,
                        help_text="Thumbnail image URL",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="Video duration (e.g., 12:45)", max_length=50
                    ),
                ),
                (
                    "views",
                    models.CharField(
                        blank=True,
                        help_text="View count (e.g., 15.2K)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "All"),
                            (1, "Tax Filing"),
                            (2, "Business Tax"),
                            (3, "Tax Planning"),
                            (4, "Sales Tax"),
                            (5, "NRP Tax"),
                            (6, "Corporate Tax"),
                            (7, "Property Tax"),
                        ],
                        default=0,
                        help_text="Video category",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="YouTube video URL or embed URL", max_length=1000
                    ),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="Whether the video is trending"
                    ),
                ),
                (
                    "new",
                    models.BooleanField(
                        default=False, help_text="Whether the video is new"
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-trending", "-new", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(help_text="CTA title", max_length=255)),
                ("description", models.TextField(help_text="CTA description")),
                (
                    "video_count",
                    models.CharField(
                        help_text="Video count (e.g., 100+)", max_length=50
                    ),
                ),
                (
                    "video_count_label",
                    models.CharField(
                        help_text="Video count label (e.g., Educational Videos)",
                        max_length=255,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(help_text="Button text", max_length=255),
                ),
                (
                    "button_link",
                    models.CharField(help_text="Button link", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Video CTA",
                "verbose_name_plural": "Video CTAs",
            },
        ),
        migrations.CreateModel(
            name="VideoHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the video hero section", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the video hero section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the video hero section"),
                ),
            ],
            options={
                "verbose_name": "Video Hero",
                "verbose_name_plural": "Video Heroes",
            },
        ),
        migrations.CreateModel(
            name="VideoSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the video section", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the video section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the video section"),
                ),
                (
                    "search_placeholder",
                    models.CharField(
                        default="Search videos...",
                        help_text="Search placeholder text",
                        max_length=255,
                    ),
                ),
                (
                    "no_results",
                    models.CharField(
                        default="No videos found",
                        help_text="No results message",
                        max_length=255,
                    ),
                ),
                (
                    "try_adjusting",
                    models.CharField(
                        default="Try adjusting your search or filters",
                        help_text="Try adjusting message",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Section",
                "verbose_name_plural": "Video Sections",
            },
        ),
        migrations.CreateModel(
            name="VideoStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "number",
                    models.CharField(
                        help_text="The statistic number or value (e.g., 50+, 5K+)",
                        max_length=255,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label describing the statistic (e.g., Video Tutorials)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Statistic",
                "verbose_name_plural": "Video Statistics",
                "ordering": ["id"],
            },
        ),
    ]
