# Generated by Django 5.2.15 on 2026-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["is_active", "is_deleted", "-trending", "-new"],
                name="video_active_trending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category", "is_active", "is_deleted"],
                name="video_category_idx",
            ),
        ),
    ]
