# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_video_active_trending_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="videocta",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="video_cta_active"
            ),
        ),
        migrations.AddIndex(
            model_name="videohero",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="video_hero_active"
            ),
        ),
        migrations.AddIndex(
            model_name="videosection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="video_section_active"
            ),
        ),
        migrations.AddIndex(
            model_name="videostatistic",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="video_stat_active"
            ),
        ),
    ]
