# Generated by Django 5.2.12 on 2026-05-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., CheckCircle)", max_length=255
                    ),
                ),
                ("title", models.CharField(help_text="CTA title", max_length=255)),
                ("description", models.TextField(help_text="CTA description")),
            ],
            options={
                "verbose_name": "Contact CTA",
                "verbose_name_plural": "Contact CTAs",
            },
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(help_text="Form title", max_length=255)),
                ("description", models.TextField(help_text="Form description")),
                (
                    "name_label",
                    models.CharField(
                        default="Full Name",
                        help_text="Name field label",
                        max_length=255,
                    ),
                ),
                (
                    "email_label",
                    models.CharField(
                        default="Email Address",
                        help_text="Email field label",
                        max_length=255,
                    ),
                ),
                (
                    "phone_label",
                    models.CharField(
                        default="Phone Number",
                        help_text="Phone field label",
                        max_length=255,
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(
                        default="Subject",
                        help_text="Subject field label",
                        max_length=255,
                    ),
                ),
                (
                    "message_label",
                    models.CharField(
                        default="Message",
                        help_text="Message field label",
                        max_length=255,
                    ),
                ),
                (
                    "submit_button_text",
                    models.CharField(
                        default="Send Message",
                        help_text="Submit button text",
                        max_length=255,
                    ),
                ),
                (
                    "loading_text",
                    models.CharField(
                        default="Sending...", help_text="Loading text", max_length=255
                    ),
                ),
                (
                    "success_message",
                    models.TextField(help_text="Success message after form submission"),
                ),
            ],
            options={
                "verbose_name": "Contact Form",
                "verbose_name_plural": "Contact Forms",
            },
        ),
        migrations.CreateModel(
            name="ContactHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the contact hero section", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the contact hero section",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the contact hero section"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Hero",
                "verbose_name_plural": "Contact Heroes",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., Phone, Email, LocationOn)",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Contact info title (e.g., Phone, Email)",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        help_text="Contact details (e.g., phone number, email address)",
                        max_length=500,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Additional info or subtitle", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ContactMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(help_text="Map section title", max_length=255),
                ),
                (
                    "iframe_url",
                    models.URLField(
                        help_text="Google Maps iframe URL", max_length=1000
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Map",
                "verbose_name_plural": "Contact Maps",
            },
        ),
        migrations.CreateModel(
            name="ContactStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., Schedule, Support)", max_length=255
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The statistic value (e.g., 24h, 10+)", max_length=255
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label describing the statistic (e.g., Response Time)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Statistic",
                "verbose_name_plural": "Contact Statistics",
                "ordering": ["id"],
            },
        ),
    ]
