# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactcta",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="contact_cta_active"
            ),
        ),
        migrations.AddIndex(
            model_name="contactform",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="contact_form_active"
            ),
        ),
        migrations.AddIndex(
            model_name="contacthero",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="contact_hero_active"
            ),
        ),
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="contact_info_active"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmap",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="contact_map_active"
            ),
        ),
        migrations.AddIndex(
            model_name="contactstatistic",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="contact_stat_active"
            ),
        ),
    ]
