# Generated by Django 5.2.12 on 2026-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "button_text",
                    models.CharField(help_text="CTA button text", max_length=100),
                ),
                (
                    "button_link",
                    models.CharField(help_text="CTA button link", max_length=500),
                ),
                (
                    "is_blog_section",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this CTA is for the blog section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog CTA",
                "verbose_name_plural": "Blog CTAs",
            },
        ),
        migrations.CreateModel(
            name="BlogHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the blog hero section", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the blog hero section", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Hero",
                "verbose_name_plural": "Blog Heroes",
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(help_text="Blog post title", max_length=255),
                ),
                (
                    "excerpt",
                    models.TextField(help_text="Short excerpt of the blog post"),
                ),
                ("author", models.CharField(help_text="Author name", max_length=255)),
                ("date", models.DateField(help_text="Publication date")),
                (
                    "read_time",
                    models.CharField(
                        help_text="Read time (e.g., '5 min read')", max_length=50
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "All"),
                            (1, "Tax Filing"),
                            (2, "Business Tax"),
                            (3, "Tax Planning"),
                            (4, "Sales Tax"),
                            (5, "NRP Tax"),
                            (6, "Corporate Tax"),
                            (7, "Property Tax"),
                        ],
                        default=0,
                        help_text="Blog category",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for blog image",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload blog image",
                        null=True,
                        upload_to="blog_posts/",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug for the blog post",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the blog section", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title for the blog section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the blog section"),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list, help_text="Categories as integer array"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Section",
                "verbose_name_plural": "Blog Sections",
            },
        ),
        migrations.CreateModel(
            name="BlogStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "number",
                    models.CharField(
                        help_text="The statistic number or value (e.g., 100+, 50K+)",
                        max_length=255,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label describing the statistic (e.g., Articles Published)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Statistic",
                "verbose_name_plural": "Blog Statistics",
                "ordering": ["id"],
            },
        ),
    ]
