# Generated by Django 5.2.12 on 2026-05-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="author",
            new_name="author_name",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_avatar",
            field=models.URLField(
                blank=True, help_text="Author avatar URL", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_bio",
            field=models.TextField(blank=True, help_text="Author bio", null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_title",
            field=models.CharField(
                blank=True, help_text="Author title/position", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content",
            field=models.JSONField(
                blank=True, default=list, help_text="Blog content blocks as JSON array"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="related_slugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Related blog post slugs as JSON array",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="List of tags as JSON array"
            ),
        ),
    ]
