# Generated by Django 5.2.12 on 2026-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_author_blogpost_author_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("paragraph", "Paragraph"),
                            ("list", "List"),
                            ("ordered-list", "Ordered List"),
                            ("quote", "Quote"),
                            ("highlight", "Highlight"),
                            ("subheading", "Subheading"),
                        ],
                        help_text="Type of content block",
                        max_length=50,
                    ),
                ),
                ("content", models.JSONField(help_text="Content data for the block")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the content block"
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(help_text="Tag name", max_length=100, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug for tag", max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="related_slugs",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="related_posts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related blog posts",
                related_name="related_to",
                to="blog.blogpost",
            ),
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_blocks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Content blocks for the blog post",
                related_name="blog_posts",
                to="blog.contentblock",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associated with the blog post",
                related_name="blog_posts",
                to="blog.tag",
            ),
        ),
    ]
