# Generated by Django 5.2.15 on 2026-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_contentblock_tag_remove_blogpost_content_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["slug"], name="blog_post_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["is_active", "is_deleted", "-date"],
                name="blog_post_active_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category", "is_active", "is_deleted"],
                name="blog_post_category_idx",
            ),
        ),
    ]
