# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpost_blog_post_slug_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogcta",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="blog_cta_active"
            ),
        ),
        migrations.AddIndex(
            model_name="bloghero",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="blog_hero_active"
            ),
        ),
        migrations.AddIndex(
            model_name="blogsection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="blog_section_active"
            ),
        ),
        migrations.AddIndex(
            model_name="blogstatistic",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="blog_stat_active"
            ),
        ),
    ]
