# Generated by Django 5.2.12 on 2026-05-10 17:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name or identifier for the benefit",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text describing the benefit", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Benefit",
                "verbose_name_plural": "Service Benefits",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_service_section",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this CTA is for a service section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the call-to-action section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description for the call-to-action section"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        help_text="Text to display on the CTA button", max_length=255
                    ),
                ),
                (
                    "button_link",
                    models.URLField(help_text="URL link for the CTA button"),
                ),
            ],
            options={
                "verbose_name": "Service CTA",
                "verbose_name_plural": "Service CTAs",
            },
        ),
        migrations.CreateModel(
            name="ServiceHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Main title for the hero section", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        help_text="Subtitle or tagline for the hero section"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Hero",
                "verbose_name_plural": "Service Heroes",
            },
        ),
        migrations.CreateModel(
            name="ServiceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the service section", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title for the service section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the service section"),
                ),
                (
                    "cta_title",
                    models.CharField(
                        help_text="Title for the call-to-action section", max_length=255
                    ),
                ),
                (
                    "cta_description",
                    models.TextField(
                        help_text="Description for the call-to-action section"
                    ),
                ),
                (
                    "primary_button",
                    models.CharField(
                        help_text="Text for the primary button", max_length=255
                    ),
                ),
                (
                    "secondary_button",
                    models.CharField(
                        help_text="Text for the secondary button", max_length=255
                    ),
                ),
                (
                    "features_label",
                    models.CharField(
                        default="Key Features:",
                        help_text="Label for the features section",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Section",
                "verbose_name_plural": "Service Sections",
            },
        ),
        migrations.CreateModel(
            name="ServiceStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "number",
                    models.CharField(
                        help_text="The statistic number or value (e.g., 500+, 15+)",
                        max_length=255,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label describing the statistic (e.g., Clients Served)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Statistic",
                "verbose_name_plural": "Service Statistics",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the service", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the service"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name or identifier for the service",
                        max_length=255,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Color code for the service (e.g., #EE1C27)",
                        max_length=255,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        help_text="Text to display on the service button",
                        max_length=255,
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Badge text to highlight the service",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "popular",
                    models.BooleanField(
                        default=False, help_text="Mark as popular service"
                    ),
                ),
                (
                    "features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="List of service features",
                        size=None,
                    ),
                ),
                (
                    "service_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="The service section this service belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="service.servicesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["id"],
            },
        ),
    ]
