# Generated by Django 5.2.12 on 2026-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesection",
            name="cta_description",
        ),
        migrations.RemoveField(
            model_name="servicesection",
            name="cta_title",
        ),
        migrations.RemoveField(
            model_name="servicesection",
            name="primary_button",
        ),
        migrations.RemoveField(
            model_name="servicesection",
            name="secondary_button",
        ),
        migrations.AlterField(
            model_name="servicecta",
            name="button_link",
            field=models.URLField(help_text="URL link for the call-to-action button"),
        ),
        migrations.AlterField(
            model_name="servicecta",
            name="button_text",
            field=models.CharField(
                help_text="Text to display on the call-to-action button", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="servicecta",
            name="is_service_section",
            field=models.BooleanField(
                default=False,
                help_text="Whether this call-to-action is for a service section",
            ),
        ),
    ]
