# Generated by Django 5.2.12 on 2026-05-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_remove_servicesection_cta_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesection",
            name="features_label",
        ),
    ]
