# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_servicesection_features_label"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="service_service_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicebenefit",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="service_benefit_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecta",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="service_cta_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicehero",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="service_hero_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="service_sect_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicestatistic",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="service_stat_active"
            ),
        ),
    ]
