# Generated by Django 5.2.12 on 2026-03-24 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("button_text", models.CharField(max_length=100)),
                (
                    "button_link",
                    models.CharField(
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "background_gradient",
                    models.CharField(
                        help_text="CSS gradient string (e.g., 'linear-gradient(135deg, #000000 0%, #333333 100%)')",
                        max_length=500,
                    ),
                ),
                (
                    "background_image_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for background image",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload background image (optional if using external URL)",
                        null=True,
                        upload_to="hero_sections/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
                "ordering": ["-created_at"],
            },
        ),
    ]
