# Generated by Django 5.2.12 on 2026-05-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(help_text="CTA title", max_length=255)),
                ("description", models.TextField(help_text="CTA description")),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email for the CTA", max_length=254
                    ),
                ),
                (
                    "is_team_section",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this CTA is for the team section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team CTA",
                "verbose_name_plural": "Team CTAs",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the team member", max_length=255
                    ),
                ),
                (
                    "position",
                    models.CharField(help_text="Job title or position", max_length=255),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="Area of specialization", max_length=255
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        help_text="Avatar initials (e.g., 'AM')", max_length=10
                    ),
                ),
                (
                    "bio",
                    models.TextField(help_text="Short biography of the team member"),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=list, help_text="List of credentials as JSON array"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True, help_text="LinkedIn profile URL", null=True
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Whether this member is featured"
                    ),
                ),
                (
                    "featured_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for featured members",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["-featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the team section", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title for the team section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the team section"),
                ),
                (
                    "credentials_label",
                    models.CharField(
                        default="Credentials:",
                        help_text="Label for credentials field",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Section",
                "verbose_name_plural": "Team Sections",
            },
        ),
    ]
