# Generated by Django 5.2.12 on 2026-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_teamcta_teammember_teamsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Team member photo",
                null=True,
                upload_to="team_members/",
            ),
        ),
    ]
