# Generated by Django 5.2.12 on 2026-05-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_teammember_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the client", max_length=255
                    ),
                ),
                (
                    "role",
                    models.CharField(help_text="Job title or role", max_length=255),
                ),
                ("company", models.CharField(help_text="Company name", max_length=255)),
                (
                    "avatar",
                    models.CharField(
                        help_text="Avatar initials (e.g., 'AH' for Ahmed Hassan)",
                        max_length=10,
                    ),
                ),
                ("rating", models.IntegerField(default=5, help_text="Rating out of 5")),
                ("testimonial", models.TextField(help_text="Client testimonial text")),
                (
                    "location",
                    models.CharField(help_text="Client location", max_length=255),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Whether this testimonial is featured"
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["-featured", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestimonialCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(help_text="CTA title", max_length=255)),
                ("description", models.TextField(help_text="CTA description")),
                (
                    "button_text",
                    models.CharField(
                        blank=True, help_text="Button text", max_length=100, null=True
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True, help_text="Button link", max_length=255, null=True
                    ),
                ),
                (
                    "is_testimonial_section",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this CTA belongs to testimonial section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial CTA",
                "verbose_name_plural": "Testimonial CTAs",
            },
        ),
        migrations.CreateModel(
            name="TestimonialSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the testimonial section", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title for the testimonial section",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the testimonial section"
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial Section",
                "verbose_name_plural": "Testimonial Sections",
            },
        ),
    ]
