# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_testimonial_testimonialcta_testimonialsection"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="herosection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="home_herosection_active"
            ),
        ),
        migrations.AddIndex(
            model_name="teamcta",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="home_teamcta_active"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="home_teammember_active"
            ),
        ),
        migrations.AddIndex(
            model_name="teamsection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="home_teamsect_active"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="home_testimonial_active"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonialcta",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="home_testimcta_active"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonialsection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="home_testimsect_active"
            ),
        ),
    ]
