# Generated by Django 5.2.12 on 2026-05-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., EmojiEvents, WorkspacePremium)",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Achievement title", max_length=255),
                ),
                ("description", models.TextField(help_text="Achievement description")),
            ],
            options={
                "verbose_name": "About Achievement",
                "verbose_name_plural": "About Achievements",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AboutCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(help_text="CTA title", max_length=255)),
                ("description", models.TextField(help_text="CTA description")),
                ("phone", models.CharField(help_text="Phone number", max_length=50)),
                ("email", models.EmailField(help_text="Email address", max_length=254)),
                (
                    "button_text",
                    models.CharField(help_text="Button text", max_length=255),
                ),
                (
                    "button_link",
                    models.CharField(help_text="Button link", max_length=255),
                ),
            ],
            options={
                "verbose_name": "About CTA",
                "verbose_name_plural": "About CTAs",
            },
        ),
        migrations.CreateModel(
            name="AboutHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the about hero section", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for the about hero section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the about hero section"),
                ),
            ],
            options={
                "verbose_name": "About Hero",
                "verbose_name_plural": "About Heroes",
            },
        ),
        migrations.CreateModel(
            name="AboutStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "number",
                    models.CharField(
                        help_text="The statistic number or value (e.g., 500+, 10+)",
                        max_length=255,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label describing the statistic (e.g., Happy Clients)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Statistic",
                "verbose_name_plural": "About Statistics",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AboutStatisticItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., People, TrendingUp)", max_length=255
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Statistic value (e.g., 500+, 10+)", max_length=255
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Statistic label (e.g., Happy Clients)",
                        max_length=255,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#EE1C27",
                        help_text="Color for the statistic",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Statistic Item",
                "verbose_name_plural": "About Statistic Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AboutStatisticSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the statistics section", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "About Statistic Section",
                "verbose_name_plural": "About Statistic Sections",
            },
        ),
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., Verified, WorkspacePremium)",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(help_text="Value title", max_length=255)),
                ("description", models.TextField(help_text="Value description")),
            ],
            options={
                "verbose_name": "About Value",
                "verbose_name_plural": "About Values",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WhoWeAre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle for who we are section", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title for who we are section", max_length=255
                    ),
                ),
                (
                    "paragraphs",
                    models.JSONField(
                        default=list, help_text="Paragraphs as JSON array"
                    ),
                ),
                (
                    "image_overlay_title",
                    models.CharField(
                        blank=True,
                        help_text="Image overlay title",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image_overlay_description",
                    models.CharField(
                        blank=True,
                        help_text="Image overlay description",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Who We Are",
                "verbose_name_plural": "Who We Are",
            },
        ),
    ]
