# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aboutachievement",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_achievement_active"
            ),
        ),
        migrations.AddIndex(
            model_name="aboutcta",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_cta_active"
            ),
        ),
        migrations.AddIndex(
            model_name="abouthero",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_hero_active"
            ),
        ),
        migrations.AddIndex(
            model_name="aboutstatistic",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_stat_active"
            ),
        ),
        migrations.AddIndex(
            model_name="aboutstatisticitem",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_statitem_active"
            ),
        ),
        migrations.AddIndex(
            model_name="aboutstatisticsection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_statsect_active"
            ),
        ),
        migrations.AddIndex(
            model_name="aboutvalue",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_value_active"
            ),
        ),
        migrations.AddIndex(
            model_name="whoweare",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="about_whoweare_active"
            ),
        ),
    ]
