# Generated by Django 5.2.12 on 2026-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterBottomSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "copyright",
                    models.TextField(
                        help_text="Copyright text (use {year} placeholder for year)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Bottom Section",
                "verbose_name_plural": "Footer Bottom Sections",
            },
        ),
        migrations.CreateModel(
            name="FooterBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(help_text="Brand name", max_length=255)),
                ("description", models.TextField(help_text="Brand description")),
                (
                    "logo_alt",
                    models.CharField(help_text="Logo alt text", max_length=255),
                ),
                (
                    "follow_us",
                    models.CharField(
                        default="Follow Us", help_text="Follow us text", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Brand",
                "verbose_name_plural": "Footer Brands",
            },
        ),
        migrations.CreateModel(
            name="FooterContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        default="Contact Us",
                        help_text="Contact section title",
                        max_length=255,
                    ),
                ),
                (
                    "address_label",
                    models.CharField(
                        default="Office Address",
                        help_text="Address label",
                        max_length=255,
                    ),
                ),
                ("address_value", models.TextField(help_text="Office address")),
                (
                    "phone_label",
                    models.CharField(
                        default="Phone", help_text="Phone label", max_length=255
                    ),
                ),
                (
                    "phone_value",
                    models.CharField(help_text="Phone number", max_length=255),
                ),
                (
                    "email_label",
                    models.CharField(
                        default="Email", help_text="Email label", max_length=255
                    ),
                ),
                (
                    "email_value",
                    models.EmailField(help_text="Email address", max_length=255),
                ),
                (
                    "business_hours_label",
                    models.CharField(
                        default="Business Hours",
                        help_text="Business hours label",
                        max_length=255,
                    ),
                ),
                (
                    "business_hours_value",
                    models.CharField(help_text="Business hours", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Footer Contact",
                "verbose_name_plural": "Footer Contact",
            },
        ),
        migrations.CreateModel(
            name="FooterLegalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("label", models.CharField(help_text="Link label", max_length=255)),
                ("url", models.CharField(help_text="Link URL", max_length=500)),
            ],
            options={
                "verbose_name": "Footer Legal Link",
                "verbose_name_plural": "Footer Legal Links",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FooterQuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("label", models.CharField(help_text="Link label", max_length=255)),
                ("url", models.CharField(help_text="Link URL", max_length=500)),
            ],
            options={
                "verbose_name": "Footer Quick Link",
                "verbose_name_plural": "Footer Quick Links",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FooterServiceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("label", models.CharField(help_text="Link label", max_length=255)),
                ("url", models.CharField(help_text="Link URL", max_length=500)),
            ],
            options={
                "verbose_name": "Footer Service Link",
                "verbose_name_plural": "Footer Service Links",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FooterSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "platform",
                    models.CharField(
                        help_text="Platform name (e.g., Facebook, Instagram)",
                        max_length=255,
                    ),
                ),
                ("url", models.URLField(help_text="Platform URL", max_length=1000)),
            ],
            options={
                "verbose_name": "Footer Social Link",
                "verbose_name_plural": "Footer Social Links",
                "ordering": ["id"],
            },
        ),
    ]
