# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footer", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="footerbottomsection",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="footer_bottomsect_active"
            ),
        ),
        migrations.AddIndex(
            model_name="footerbrand",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="footer_brand_active"
            ),
        ),
        migrations.AddIndex(
            model_name="footercontact",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="footer_contact_active"
            ),
        ),
        migrations.AddIndex(
            model_name="footerlegallink",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="footer_legallink_active"
            ),
        ),
        migrations.AddIndex(
            model_name="footerquicklink",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="footer_quicklink_active"
            ),
        ),
        migrations.AddIndex(
            model_name="footerservicelink",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="footer_servicelink_active"
            ),
        ),
        migrations.AddIndex(
            model_name="footersociallink",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="footer_sociallink_active"
            ),
        ),
    ]
